const newUserData = [
    'john_doe',
    'jane_smith',
    'mary_johnson',
    'david_williams',
    'susan_davis',
    'michael_clark',
    'sarah_walker',
    'kevin_adams',
    'lisa_martin',
    'steven_jackson',
    'elizabeth_lee',
    'thomas_hall',
    'emily_roberts',
    'daniel_baker',
    'olivia_white',
    'william_green',
    'jennifer_harris',
    'chris_wright',
    'natalie_morris',
    'james_carter',
    'barbara_thompson'
];

const newUserEmails = [
    'john_doe@gmail.com',
    'jane_smith@gmail.com',
    'mary_johnson@gmail.com',
    'david_williams@gmail.com',
    'susan_davis@gmail.com',
    'michael_clark@gmail.com',
    'sarah_walker@gmail.com',
    'kevin_adams@gmail.com',
    'lisa_martin@gmail.com',
    'steven_jackson@gmail.com',
    'elizabeth_lee@gmail.com',
    'thomas_hall@gmail.com',
    'emily_roberts@gmail.com',
    'daniel_baker@gmail.com',
    'olivia_white@gmail.com',
    'william_green@gmail.com',
    'jennifer_harris@gmail.com',
    'chris_wright@gmail.com',
    'natalie_morris@gmail.com',
    'james_carter@gmail.com',
    'barbara_thompson@gmail.com'
];

const newFriendNames = [
    'jane_smith',
    'mary_johnson',
    'david_williams',
    'susan_davis',
    'michael_clark',
    'sarah_walker',
    'kevin_adams',
    'lisa_martin',
    'steven_jackson',
    'elizabeth_lee',
    'thomas_hall',
    'emily_roberts',
    'daniel_baker',
    'olivia_white',
    'william_green',
    'jennifer_harris',
    'chris_wright',
    'natalie_morris',
    'james_carter',
    'barbara_thompson',
    'john_doe'
];

const newThoughtText = [
    'I am feeling great today',
    'I had an amazing weekend',
    'Pizza is my favorite food',
    'I love hiking in the mountains',
    'Reading a good book is so relaxing',
    'Greetings, fellow pirates!',
    'What\'s cooking, Doc?',
    'Contemplating the mysteries of the universe',
    'Chopping wood like a pro lumberjack',
    'Bugs Bunny is a classic character',
    'That\'s a wrap, folks!',
    'Hunting for wabbits with great enthusiasm',
    'I tawt I taw a puddy tat!',
    'Beep beep! Fast and furious!',
    'I possess superior intellect',
    'Howdy, folks!',
    'That elusive rabbit keeps escaping!',
    'Yeehaw! Cowboy spirit!',
    'Baking delicious blueberry pies',
];

const newReactions = [
    'I concur',
    'I dissent',
    'I\'m a fan',
    'I strongly dislike',
    'I adore it',
    'I\'m indifferent',
    'I\'m uncertain',
    'I\'m confident',
    'This is unexciting',
    'Bugs Bunny is *EPIC*',
    'Speech impediments are no big deal',
    '*whispers* The rabbit will outsmart you again',
    'You did! You did see a puddy tat!',
    'I\'m a super-duper genius',
    'I beg to differ',
    'And a warm howdy to you too',
    'The rabbit always gets away!',
    'I\'m the fastest mouse in all of Mexico',
    'LEAVE THAT CAT BE!',
    'I\'m a rootin\' tootin\' cowboy',
    'I appreciate your blueberry pies!',
];

// Export the renamed data for use in seed.js
module.exports = { newUserData, newUserEmails, newFriendNames, newThoughtText, newReactions };
